name: "Run Aries Test Harness"
description: "Run the Aries Test Harness test suite with the specified Agents"
author: "iancostanzo@gmail.com"
inputs:
  DEFAULT_AGENT:
    description: "Default agent image for all roles"
    required: false
    default: "acapy"
  BOB_AGENT:
    description: "Specific agent image for the bob role"
    required: false
    default: "acapy"
  REPORTING:
    description: "Use formal reporting engine"
    required: false
    default: "-r allure"
  REPORT_PROJECT:
    description: "Name of the project the Allure Service is using to store these results"
    required: false
    default: "general"
  TEST_SCOPE:
    description: "Set of flags that defines the test scope"
    required: false
    default: "-t @AcceptanceTest -t ~@wip"
runs:
  using: "composite"
  steps:
    - name: build-test-harness
      run: ./manage build -a ${{ inputs.DEFAULT_AGENT }} -a ${{ inputs.BOB_AGENT }}
      shell: bash
      working-directory: test-harness
    - name: run-test-harness-acapy
      run: PROJECT_ID=${{REPORT_PROJECT}} ./manage run -d ${{ inputs.DEFAULT_AGENT }} -b ${{ inputs.BOB_AGENT }} ${{ inputs.REPORTING }} ${{ inputs.TEST_SCOPE }}
      shell: bash
      env:
        NO_TTY: "1"
      working-directory: test-harness
branding:
  icon: "mic"
  color: "purple"
