name: test-harness-acapy-full
# RUNSET_NAME: "ACA-PY to ACA-Py All Tests"
# Scope: AIP 1.0
# Exceptions: None
# SKIP
# 
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents. The runset runs every test in the suite
# including those that are marked as works in progress.
#
# Current
# 
# Half of the tests in the suite are working. "work in progress" tests were removed as they are
# not expected to pass. This is the reason for the drop in total test count in the Allure Reports
# We'll assess and document the other tests that are not working and update.
# this status.
# 
# *Status Note Updated: 2021.03.18*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness
        uses: ./test-harness/actions/run-test-harness
        with:
          BUILD_AGENTS: "-a acapy-main"
          TEST_AGENTS: "-d acapy-main"
          TEST_SCOPE: "-t ~@wip"
          REPORTING: "-r allure -e comparison"
          REPORT_PROJECT: acapy-full
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
