name: test-harness-acapy-acapy
# RUNSET_NAME: "ACA-PY to ACA-Py Passing Tests"
# Scope: AIP 1.0, AIP 2.0 (RFC0023 Only)
# 
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents. The runset runs all of the tests in the suite
# that are expected to pass given the current state of ACA-Py support for AIP 1 and 2.
#
# Current
# 
# All of the tests being executed in this runset are passing.
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness
        with:
          DEFAULT_AGENT: acapy-master
          BOB_AGENT: acapy-master
          REPORT_PROJECT: acapy  
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy 
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
